### ISSUE TITLE
Uncaught ReferenceError: fullpage is not defined

### ISSUE THREAD

**Issue by usulla** [alvarotrigo/react-fullpage#14]
Hi!

Please help install the plugin.
Writes an error:

react-fullpage.js:115 Uncaught ReferenceError: fullpage is not defined

What could be the reason?

**Comment by alvarotrigo** [comment]
Please check the available demo and see if what you might be missing. 

If you still have the issue please provide a reproduction i can check. Feel free to use de codepen on the docs.

**Comment by usulla** [comment]
Now the error is now:
react-fullpage.js:115 Uncaught TypeError: Cannot read property 'classList' of undefined

Site:
http://demo4.landmary.ru/

**Comment by alvarotrigo** [comment]
Try to reproduce the issue on the Codepen demo:
https://codepen.io/alvarotrigo/pen/zpQmwq

Or on https://codesandbox.io.

And please add the JS code you are using too.

**Comment by usulla** [comment]
If I include to index.html     
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
then I see this error

**Comment by alvarotrigo** [comment]
Ok, I was able to reproduce it now in a CodeSandbox:
https://codesandbox.io/s/qlrkzlqrr4

I'll investigate it!

**Comment by cmswalker** [comment]
@alvarotrigo seems that `fullpage.js/vendors/scrolloverflow` is not providing the global `fullpage` variable that this lib relies on. Order matters, so the react lib must be imported first in order to provide fullpage. Believe this should fix it (updated order in example as well) https://github.com/alvarotrigo/react-fullpage/pull/15

**Comment by alvarotrigo** [comment]
> Order matters, so the react lib must be imported first in order to provide fullpage.

I still have the same issue even after moving it down?
https://codesandbox.io/s/qlrkzlqrr4

**Comment by cmswalker** [comment]
Interesting, it works when you run the example in the repo. What is the difference between that sandbox and the working one you forked it from?

**Comment by alvarotrigo** [comment]
@cmswalker as far as I know there's no difference on the HTML and JS files, as I just copied it from the example.

**Comment by alvarotrigo** [comment]
@cmswalker apparently the error is in [this line](https://github.com/alvarotrigo/fullPage.js/blob/3.0.2/dist/fullpage.js#L3868).  It seems it knows about `window.jQuery` and `window.fullpage` but fails to recognise `fullpage` on the IIFE?

Replacing `(jQuery,fullpage)` for `(window.jQuery,window.fullpage)` seems to solve the issue.

**Comment by cmswalker** [comment]
I see, yes it's likely due to aliasing in webpack. Passing the full path will work. Or we could add externals to the webpack config as a better long term solution

```js
externals: {
        $: 'window.jQuery',
        jQuery: 'window.jQuery',
		fullpage: 'window.fullpage'
    },
```

**Comment by alvarotrigo** [comment]
@cmswalker whatever you think it's a better solution. I can as well just use `window.jQuery` and `window.fullpage` on the fullpage code too, to be consistent.

**Comment by cmswalker** [comment]
yeah maybe fix it at the root, that way if others are consuming it via webpack it'll alleviate their issues as well

**Comment by alvarotrigo** [comment]
Fixed [on dev](https://github.com/alvarotrigo/fullPage.js/commit/ca34e93eb5ac85dd5768aabc0990dd18ee231d0d)! To be merged on the next fullPage.js relase 3.0.3!

**Comment by alvarotrigo** [comment]
Fullpage.js 3.0.3 is now available. 
Waiting to solve #https://github.com/alvarotrigo/react-fullpage/issues/33 in order to release a new version of react-fullpage.js with fullPage.js 3.0.3 as a dependency.

**Comment by cmswalker** [comment]
bumped in https://github.com/alvarotrigo/react-fullpage/pull/35 .
