### ISSUE TITLE
How to use parallax plugin in react

### ISSUE THREAD

**Issue by anshuraj** [alvarotrigo/react-fullpage#31]
I recently purchased the parallax plugin. How do I make it work in react? I'm getting following error after importing the plugin file:

Line 8:  'fp_utils' is not defined      no-undef
Line 8:  'fp_utils' is not defined      no-undef
Line 8:  'fullpage_api' is not defined  no-undef

**Comment by alvarotrigo** [comment]
Can you please provide us with the code you use to import the files?

You can take a look at [the example in the docs](https://github.com/alvarotrigo/react-fullpage#examples)

Basically you import it before react-fullpage and then just use whatever option you need to use. In this case `parallax:true` and the html elements `<div class="fp-bg"></div>` as detailed in the [parallax docs](https://github.com/alvarotrigo/fullPage.js/wiki/Extension---Parallax).

For example:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import './fullpage.parallax.min' // Optional. When using fullpage extensions
import ReactFullpage from '@fullpage/react-fullpage';


const fullpageOptions = {
  parallax: true
};

const FullpageWrapper = fullpageProps => (<ReactFullpage
  {...fullpageProps}
  render={({ state, fullpageApi }) => {
    return (
      <div>
        <div className="section">
          <div className="fp-bg"></div>
          <p>Section 1 (welcome to fullpage.js)</p>
          <button onClick={() => fullpageApi.moveSectionDown()}>Click me to move down</button>
        </div>
        <div className="section">
          <div className="fp-bg"></div>
          <p>Section 2</p>
        </div>
      </div>
    );
  }}
/>);

ReactDOM.render(<FullpageWrapper {...fullpageOptions} />, document.getElementById('react-root'));
```

Notice you'll have to add the background to the `.fp-bg` elements instead of to the section itself. As detailed in the parallax docs.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! There's actually some bug on the component!
We'll check it out!

**Comment by alvarotrigo** [comment]
No worries @cmswalker, this issue is directly related with the DOM issue #33.
Once that gets fixed this will get fixed too. 

And yeah, as extensions like parallax are purchased and not accessible through npm, people might have them through relative paths. 

>  I say we take it out of the example

Yeah we can just comment it so people won't have issues if they just copy and paste it all.
Although I think its good to have in there so people find any reference to its usage in the docs in case they want to use extensions.

```javascript 
import React from 'react';
import ReactDOM from 'react-dom';
import 'fullpage.js/vendors/scrolloverflow' // Optional. When using scrollOverflow:true

// Optional. When using fullpage extensions
//import './fullpage.scrollHorizontally.min'

import ReactFullpage from '@fullpage/react-fullpage';
```

**Comment by cmswalker** [comment]
👍

**Comment by alvarotrigo** [comment]
Docs updated!

**Comment by anshuraj** [comment]
Do I need to update my plugin file as well? I'm still getting the same error even after updating to the latest version of react-fullpage 0.1.1.

**Comment by alvarotrigo** [comment]
I'll check it out!

**Comment by alvarotrigo** [comment]
@anshuraj yeap, I can confirm the error stills there. However, now the parallax effects works as expected right?

So far, you can avoid it by adding the `active` and the `fp-section` classes to the section that will be the starting point:

```html
<div className="section fp-section active">
```

@cmswalker the error related with the creation of the dummy section and the double initialisation. I'll try to see if we manage get rid of it.

**Comment by anshuraj** [comment]
@alvarotrigo Can you please confirm if I will need to update the parallax plugin fiile (fullpage.parallax.min.js) for this to work because I'm still getting the same error even in the latest version?

![image](https://user-images.githubusercontent.com/4736201/47078172-4f898880-d220-11e8-971e-cb22f8447e27.png)

This is my import in the react component:
```
import './fullpage.parallax.min';
import ReactFullpage from '@fullpage/react-fullpage';
```

If it is working it will be awesome if you put together an example codesandbox for the parallax plugin.
If I have to update my plugin file please do tell how do I get the latest working plugin file.

**Comment by alvarotrigo** [comment]
What version number you have of the parallax file? Check the credit comments.

**Comment by anshuraj** [comment]
fullpage.js Parallax Effect Extension 0.1.4 for fullPage.js v3

**Comment by alvarotrigo** [comment]
@anshuraj what version of react-fullpage are you using? You should be using now the latest 0.1.2.

**Comment by anshuraj** [comment]
Yes, I'm using the latest 0.1.2 version.

**Comment by alvarotrigo** [comment]
Can you please [contact me](https://alvarotrigo.com/#contact) with a link to a codesandbox reproduction of the issue?

**Comment by alvarotrigo** [comment]
@robinzimmer1989 we still working on it. 
This issue is directly related with https://github.com/alvarotrigo/react-fullpage/issues/27 which I've just opened again in an attempt to see if we can provide a better solution for it.

**Comment by alvarotrigo** [comment]
This is fixed now in 0.1.3.

**Comment by robinzimmer1989** [comment]
Hi, I've upgraded to version 0.1.3 but still getting the error message:

`/(...)/fullpage.scrollHorizontally.min.js`
`8:63   error    'fp_utils' is not defined                                              no-undef`
`8:74   error    'fp_utils' is not defined                                              no-undef`
`8:87   error    'fullpage_api' is not defined                                          no-undef`
`8:158  error    Expected an assignment or function call and instead saw an expression  no-unused-expressions`
`8:302  warning  Unexpected use of comma operator                                       no-sequences`
`8:330  warning  Expected '!==' and instead saw '!='                                    eqeqeq`
`8:341  error    'fullpage_api' is not defined                                          no-undef`
`8:395  error    'fullpage_api' is not defined                                          no-undef`
`8:431  warning  Unexpected use of comma operator                                       no-sequences`
`8:531  warning  Unexpected use of comma operator                                       no-sequences`


I'm importing the scripts the following way:
`import "./fullpage.scrollHorizontally.min"; // Scroll Horizontally Extension 0.0.2 for fullPage.js v3`
`import ReactFullpage from "@fullpage/react-fullpage";`

Any ideas?

**Comment by alvarotrigo** [comment]
I can not reproduce your issue.

Can you please [contact me](https://alvarotrigo.com/#contact) and provide me with a reproduction of your issue in [codesandbox](https://codesandbox.io/)?

**Comment by anshuraj** [comment]
I agree with @robinzimmer1989 
Do we have to update our plugin file? I earlier sent an email with a codesandbox link. I updated the react-fullpage version to latest. Some minor bugs are gone now, but still unable to get the parallax plugin work.

I would be great if you can provide us a sample code/codesandbox with implementation of the parallax plugin. The documentation is not enough on how to integrate the plugin for the react-fullpage library.

**Comment by alvarotrigo** [comment]
@anshuraj no need to update the parallax extension. 

Here you have a full example of its implementation. Nothing new that is not said on the docs. 
Basically:

- Import the parallax file
- Add the parallax option 
- Add the CSS styles to set the image per section
- Make sure you do not use the option `sectionsColor`

```js
import React from 'react';
import ReactDOM from 'react-dom';
import ReactFullpage from '../../components';

//import 'fullpage.js/vendors/scrolloverflow'; // Optional. When using scrollOverflow:true

import './fullpage.parallax.min'; // Optional. When using scrollOverflow:true

const originalColors = ['#282c34', '#ff5f45', '#0798ec'];

class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      sectionsColor: [...originalColors],
      fullpages: [
        {
          text: 'section 1',
          id: Math.random(),
        },
        {
          text: 'section 1',
          id: Math.random(),
        },
        {
          text: 'section 1',
          id: Math.random(),
        }
      ],
    };
  }

  onLeave(origin, destination, direction) {
    console.log('onLeave', { origin, destination, direction });
    // arguments are mapped in order of fullpage.js callback arguments do something
    // with the event
  }

  handleChangeColors() {
    const newColors = this.state.sectionsColor[0] === 'yellow' ? [...originalColors] : ['yellow', 'blue', 'white']
    this.setState({
      sectionsColor: newColors,
    });
  }

  handleAddSection() {
    this.setState((state) => {
      const { fullpages } = state;
      const { length } = fullpages;
      fullpages.push({
        text: `section ${length + 1}`,
        id: Math.random(),
      });

      return {
        fullpages: [...fullpages],
      };
    });
  }

  handleRemoveSection() {
    this.setState((state) => {
      const { fullpages } = state;
      const newPages = [...fullpages];
      newPages.pop();

      return { fullpages: newPages };
    });
  }

  render() {
    const { fullpages } = this.state;

    if (!fullpages.length) {
      return null;
    }

    return (
      <div className="App">
        <ReactFullpage
          navigation
          parallax
          onLeave={this.onLeave.bind(this)}
          render={comp => console.log('render prop change') || (
            <ReactFullpage.Wrapper>
              {fullpages.map(({ text, id }) => (
                <div key={id} className="section">
                  <div class="fp-bg"></div>
                  <h1>{text}</h1>
                </div>
              ))}
            </ReactFullpage.Wrapper>
          )}
        />
      </div>
    );
  }
}

const rootElement = document.getElementById('react-root');
ReactDOM.render(<App />, rootElement);
```  

And the index.html file in the `examples/dist/` folder:
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
    .fp-bg{
        transform: translate3d(0,0,0);
        -webkit-backface-visibility: hidden; /* Chrome, Safari, Opera */
        backface-visibility: hidden;
        background-image: url('https://i2.wp.com/beebom.com/wp-content/uploads/2016/01/Reverse-Image-Search-Engines-Apps-And-Its-Uses-2016.jpg');
        background-size: cover;
        background-position: center 80%;
    }
    </style>
</head>
<body>
    <div id="react-root"></div>
</div>
<script src="main.js"></script>
</body>
</html>
```

**Comment by lardi** [comment]
Is this example still working?
Because I tried this example but it's not work with me.

**Comment by alvarotrigo** [comment]
@lardi you can find an example of how to use extensions in the docs:
https://github.com/alvarotrigo/react-fullpage#examples

Then you'll just need to pass the necessary options, in your case `parallax:true`. 

You can also find an example of this in the example files, under comments: 
https://github.com/alvarotrigo/react-fullpage/blob/master/examples/react/src/index.js#L11

**Comment by emilol** [comment]
@alvarotrigo I notice you've linked to a snippet with a commented out extension. Do you have a sample somewhere that works at runtime?

Perhaps it would be best to provide a minimal sample with no other libraries/extensions that demonstrates the working extension. The linked snippets fall a bit short of demonstrating how the pieces hang together.

If you can provide a working sample it could help others understand what they are missing.

**Comment by alvarotrigo** [comment]
> @alvarotrigo I notice you've linked to a snippet with a commented out extension. Do you have a sample somewhere that works at runtime?

Nope, because extensions files are not public :) Therefore I can't provide a working example.
Just uncomment the line and replace it for your extension filename and the right path and it should work out of the box. 

> Perhaps it would be best to provide a minimal sample with no other libraries/extensions that demonstrates the working extension. The linked snippets fall a bit short of demonstrating how the pieces hang together.

What do you mean? 
There are no extra libraries/extensions on those examples. Just fullPage.js.

**Comment by emilol** [comment]
Ok, fair. You can't provide an example because it would undermine your business model. You do _have_ a working example though, right?

Suppose you were to make something that worked at runtime, then remove the contents of the parallax extension, then push that code somewhere. You can put your hand on your heart and say if I plug in the extension I've downloaded from gumroad that it will definitely work?

I'm seeing a few people here having the same issue I'm having, and I'm not seeing any clues as to what I might be doing wrong in the snippets you have linked to.

**Comment by alvarotrigo** [comment]
> Suppose you were to make something that worked at runtime,

What do you mean by that?
Without compiling the sources with npm build / run?

Can you please elaborate what's the problem you face with this example?
https://github.com/alvarotrigo/react-fullpage/blob/master/examples/react/src/index.js#L11

Perhaps this way I would be able to understand better what you mean :)
