### ISSUE TITLE
Not ending up on the first section after Next.js page transition

### ISSUE THREAD

**Issue by gustavlrsn** [alvarotrigo/react-fullpage#327]
### Description
Hello! I recently upgraded to v4 when I noticed this issue, the bug is not in v3.

I have multiple pages in Next.js with different fullpage sections, when doing a page transition I'm not always ending up on the first section. 

https://user-images.githubusercontent.com/1552194/168397655-5cb7a63b-3103-4372-8e43-aaced4cd0651.mov

### Link to isolated reproduction with no external CSS / JS
https://codesandbox.io/s/react-fullpage-page-transition-bug-5qre5d?file=/components/fullpage.js
(might need to open a new terminal and run `yarn start` and open a new browser in `:3001`, seems to be some issue with CodeSandbox)

### Steps to reproduce it
1. Click down the sections until you get to the last section
2. Click link to the second page
3. See that you end up on section number 2 and not the first one

### Versions 
Chrome, Mac OS

**Comment by alvarotrigo** [comment]
Thanks for reporting it!
I'll investigate it.

**Comment by dev-lukian** [comment]
Was this ever fixed? I am still having issues.

**Comment by alvarotrigo** [comment]
Not yet.

**Comment by dev-lukian** [comment]
@alvarotrigo Are there plans of fixing this soon? I am about to launch a project and this is a bug that is refraining me from doing so.

**Comment by alvarotrigo** [comment]
No plan. I might need external help to figure this out, as  I'm not heavy on React or Next :)

**Comment by skoteskote** [comment]
Hi, any estimate on when it will be resolved? This issue is currently blocking us from upgrading to v4, which we really would like to do as it's much smoother.

**Comment by alvarotrigo** [comment]
@skoteskote I've just tested it again and I can not reproduce the issue anymore here:
https://codesandbox.io/s/react-fullpage-page-transition-bug-5qre5d?file=/components/fullpage.js

Can you verify you still have the issue?

It might have been solved when updating the React wraper to the latest fullPagejs version?

**Comment by dev-lukian** [comment]
I fixed this issue by adding `fullpage_api.silentMoveTo(1)` right after I switch to another page.

**Comment by devAdrish** [comment]
Issue still exists. I was trying to do it with` fullpage_api.moveTo(1)` but was facing #405.
@dev-lukian thanks for this.
